image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/xstar97/my-proxy-service
  tag: v0.0.1@sha256:2ef9bb1b94f24966e9e52bc398e9c1eb52f1582f22ffe2ebc3629cd2977e49c4

operator:
  register: false
  
portal:
  open:
    enabled: true
    
persistence:
  token:
    projected:
      mountPath: /service-account
      sources:
        - serviceAccountToken:
            expirationSeconds: 3600
            path: token
          
    
workload:
  main:
    enabled: true
    podSpec:
      containers:
        container-name:
          env:
            PORT: 3000    
          args:
            - --api-file /service-account/token
            - --proxy-target http://tckubeapps:8080
            - --auth-token-header authorization

service:
  main:
    enabled: false
    ports:
      main:
        port: 3000
  tckubeapps:
    enabled: true
    primary: true
    expandObjectName: false
    labels:
      truecharts.org/flagged: "true"
    selectorLabels:
      app.kubernetes.io/component: frontend
      truecharts.org/kahack: frontend
    ports:
      tckubeapps:
        enabled: true
        primary: true
        port: 8080
        targetPort: 8080

serviceAccount:
  kubeapps-operator:
    enabled: true
    primary: true

secret:
  kubeapps-operator-token:
    enabled: true
    type: kubernetes.io/service-account-token
    annotations:
      kubernetes.io/service-account.name: kubeapps-operator
    stringData: "-"

rbac:
  kubeapps-operator:
    enabled: true
    primary: true
    clusterWide: true
    allServiceAccounts: true
    rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]

kubeapps:
  frontend:
    podLabels:
      truecharts.org/kahack: frontend
  apprepository:
    initialRepos:
      - name: truecharts
        url: https://charts.truecharts.org
